--- Makefile.orig	2010-12-06 20:14:25.000000000 +0100
+++ Makefile	2010-12-06 20:14:59.000000000 +0100
@@ -1,5 +1,5 @@
 
 test:
-	@./support/expresso/bin/expresso -I lib test/*.test.js
+	@/usr/bin/expresso -I lib test/*.test.js
 
-.PHONY: test
\ No newline at end of file
+.PHONY: test
